### ISSUE TITLE
Asrock x370 Killer support?

### ISSUE THREAD

**Issue by nikita240** [dcerisano/RGB-LED-Motherboard-Header-Driver-App#1]
Is there anything out there to point me in the right direction for writing an RGB driver for the Asrock x370 boards?

**Comment by dcerisano** [comment]
Asrock x370 mobos use the NCT6779 SIO chip which actually has a published [datasheet](http://v-comp.kiev.ua/download/NCT6779D.pdf).

It should be fairly straight forward to derive the port bank protocols. Remember you will need a [signed port access library](https://github.com/ellysh/InpOut32) to build a driver on Windows.

Also see [RWeverything](http://rweverything.com/) as a testing tool. Be careful with it!

To be honest, I am now writing [software](https://www.npmjs.com/package/rgb-led-matrix) for AT based RGB USB controllers, which are addressable and way more fun than messing with proprietary SIO based RGB.

**Comment by nikita240** [comment]
Thank you so much! I'll report any findings or updates.

**Comment by r-tanner-f** [comment]
Will be looking in to this myself shortly. @Nikita240 did you make any headway? Get stuck somewhere?

**Comment by nikita240** [comment]
@r-tanner-f unfortunately I haven't started. Been busy with other projects.

Keep us updated though!
