### ISSUE TITLE
X470 Taichi

### ISSUE THREAD

**Issue by RepeatingDigits** [dcerisano/RGB-LED-Motherboard-Header-Driver-App#6]
I don't like opening issues requesting very specific stuff, but on theory, would an eventual windows version of this work on a X470 Taichi? I have no idea if it has a published SIO datasheet.
Asrock's Polychrome RGB is driving me insane with it's poor "Music" driver compatibility.

**Comment by dcerisano** [comment]
Your board must have a NCT6795D SIO chip. Not likely this will run on anything other than MSI boards.
